FROM alpine:3.18

# Add the Edge repository
# TODO 2. Remove edge repository once it's mainstreamed?
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories

# Install packages
RUN apk update && \
    apk add --no-cache postgresql17-client tzdata

# Set timezone
ARG APPLICATION_TZ
RUN cp /usr/share/zoneinfo/${APPLICATION_TZ} /etc/localtime

# Remove now unessisary packages
RUN apk del tzdata

COPY scripts /scripts
ENTRYPOINT ["/bin/sh", "/scripts/entrypoint.sh"]
